### ISSUE TITLE
controllers/qwench.php required failed

### ISSUE THREAD

**Issue by yiqun** [anantgarg/Qwench#8]
Warning: include(MY_Qwench_INSTALL_PATH/controllers/qwench.php): failed to open stream: No such file or directory in MY_Qwench_INSTALL_PATH/index.php on line 48

**Comment by etfb** [comment]
This is caused by an erroneous "/qwench/" instead of $basePathNS in controllers/questions.php.  Looks like the program originally expected to always be installed in the named subdirectory, but then the devs added the option to put it elsewhere but forgot to make all the conversions to the new way of working.

Apologies to yiqun for a six-year-old answer!

**Comment by anantgarg** [comment]
@etfb thank you for taking the time to answer this really-really-really-old question :)

**Comment by anantgarg** [comment]
I've fixed the issue.
